### ISSUE TITLE
Network Build Errors

### ISSUE THREAD

**Issue by mtbnski** [Esri/street-data-processing-tools#15]
I am building a network with the latest TomTom data, and have been getting build errors. This is an example of the error: `SourceName: RestrictedTurns, ObjectID: 873, The edges of the turn element conflict with existing interior/exterior edges.` There are 537 errors with the 2017.03 unj data. I am trying to understanding what this error means and if it is possible to fix the errors. The network otherwise builds fine and I am able to route after it is built.

**Comment by aHatakeyama** [comment]
The errors are due to the result of the maneuver data provided by HERE and TomTom do not match the turn modeling in network datasets.  Compare the documentation for [Turns in the network dataset](http://desktop.arcgis.com/en/arcmap/latest/extensions/network-analyst/turns-in-the-network-dataset.htm) with the documentation of your street data for further details.

**Comment by mmorang** [comment]
My colleague answered this question in 2018, and there have been no further updates since then, so I'm going to close this issue.  If you feel that the issue has not been resolved adequately, feel free to reopen!

Build errors related to turns still occur in the new ArcGIS Pro version of the Street Data Processing Tools, but as my colleague explained, this has to do with the data provided by HERE and TomTom not always matching the requirements of turn modeling in a network dataset.  It's likely that you will need to manually review and edit the turn features that cause the build errors.  Here is some updated [documentation about network build errors](https://pro.arcgis.com/en/pro-app/latest/help/analysis/networks/network-dataset-build-errors.htm).
