### ISSUE TITLE
Tool crashes with large datasets

### ISSUE THREAD

**Issue by Ketar1** [Esri/street-data-processing-tools#17]
I am running the tool using ArcGIS 10.5.1 with TomTom data. The nw feature class I am using is 11gb and it covers the entire USA. Each time I input the nw feature class into the tool, ArcMap crashes right away. Can you let me know what could be causing this? Has anyone run this tool for the entire USA?

**Comment by mmorang** [comment]
I realize this issue is quite old. This is likely a memory issue. We are not likely to address any performance issues in the ArcMap version of this tool, and because ArcMap is a 32bit application, there probably isn't much we can do anyway.

Please try the new ArcGIS Pro version of the tool, which should have better performance and uses a 64bit application natively. We have tested this with a TomTom MultiNet North America dataset and were able to run it successfully in a reasonable amount of time.
