### ISSUE TITLE
Crash when using HERE Data

### ISSUE THREAD

**Issue by shaharbukra** [Esri/street-data-processing-tools#18]
We try using the tool "Process NAVSTREETS™ Street Data"
and the tool keep on crashing for us.
Any idea how to make it work?

We use ArcMap 10.5.1

![image](https://user-images.githubusercontent.com/3829015/34144225-4c0e5eee-e499-11e7-8a65-3d88ca58cef5.png)

Thanks

**Comment by mmorang** [comment]
Crashes in the ArcMap Street Data Processing Tools typically resulted from resource limitations, such as the tool running out of memory.  A new version of the tool for processing HERE data is now available for ArcGIS Pro.  If you're still processing HERE data, please try this new tool version and let us know if you still experience hangs and crashes.  Because ArcGIS Pro is a 64-bit application and because the new tool was fully rewritten to be less resource intensive, we don't expect the same types of limitations that the old ArcMap version had.

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
