### ISSUE TITLE
WalkTime for Multinet

### ISSUE THREAD

**Issue by chritomix** [Esri/street-data-processing-tools#28]
Hi,
my question is why tool for Multinet does not include WalkTime impedance vs the one existing for Navstreets?

**Comment by aHatakeyama** [comment]
Hi @chritomix.  My apologies on the delay in this response.

The WalkTime cost attribute created by the NAVSTREETS tool uses a constant walking speed that defaults to 5 km/h, but can be configured at solve time.  Because it's a constant speed for all street segments, this cost attribute behaves identically to the distance attributes that are also created; the only difference being the units of impedance being reported.  The WalkTime cost attribute is created to accompany the Walking restriction attribute in the Walking Time travel mode created by the NAVSTREETS tool.

Unlike the NAVSTREETS data, the MultiNet data does not have any pedestrian restriction information, so there is no need to create any pedestrian-specific travel modes, and there is no need to create a cost attribute that behaves nearly identically to the distance attributes already created by the MultiNet tool.

Please let me know if you have any further questions.  Thanks!

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
