### ISSUE TITLE
issue arcgis 10.4.1

### ISSUE THREAD

**Issue by chritomix** [Esri/street-data-processing-tools#29]
Hi
I am using arcgis 10.4.1 (version of esri software and version of the tool). Recently I am having the issue to build network. It is failing at the last moment (the tool is trying to add restricted turns, or errors...)
It seems to that arccatolog blocks access to temporary folder, and at the same time the tool is trying to access it. any idea?
![image](https://user-images.githubusercontent.com/32699393/49933423-e21a7100-fecb-11e8-8692-582bbfd3893d.png)

**Comment by chritomix** [comment]
just to let you know, that normally I have a custom tool which is calling my script, inside wchich I am importing StreetDtaProcessingTool and next executing.
 And this is where it fails.
However, I just tested and if I execute my script directly using command line - it worked. No issue with blocking access to any folder.

**Comment by mmorang** [comment]
I apologize that we never responded to this question.

This sounds like a file lock error of some sort.  Did you ever resolve the issue, or was your workaround of running the script from the command line adequate?

A new version of the Street Data Processing Tools in ArcGIS Pro is now available.  Because ArcMap is now in mature support as a product, please migrate your data processing workflows to ArcGIS Pro using the new tools if you haven't already, and let us know if you're still experiencing problems with automating your workflow.

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
