### ISSUE TITLE
Process Large ND

### ISSUE THREAD

**Issue by xeir83** [Esri/street-data-processing-tools#32]
Im having trouble compiling USA + Canada to one ND. 
I have tested the 10.3 tool together with arcmap 10.3, as well as the latest 10.6 tool together with arcmap 10.6.

The 10.3 tool crashes with an out of memory exception - even thou i have enough disk space. (140GB + 300gb)

The 10.6 tool crashes silently without any errors when running from python, but when running from ArcMap it crashes with exit code: 0xc0000409

I have seen more users with a similar problem here, but no soloution. 
As far as i understand it is not possible to run this tool trough 64 bit version of python?

**Comment by mmorang** [comment]
I realize this issue is quite old. We are not likely to address any performance issues in the ArcMap version of this tool, and because ArcMap is a 32bit application, there probably isn't much we can do anyway.

Please try the new ArcGIS Pro version of the tool, which should have better performance and uses a 64bit application natively.  We have tested this with a TomTom MultiNet North America dataset and were able to run it successfully in a reasonable amount of time.
