### ISSUE TITLE
HERE™ NAVSTREETS™ data building with fieldnames greater than 31 chars

### ISSUE THREAD

**Issue by dbarretteuk** [Esri/street-data-processing-tools#48]
I have encountered an issue  with a network using HERE™ NAVSTREETS™ with Trucking attributes. The source data for the streets and restricted turns results in the following fieldnames being included:

streets feature class:

FT_KingpinToRearAxleLengthLimit_Meters
FT_SemiOrTractorWOneOrMoreTrailersProhibited
FT_ExplosiveAndFlammableProhibited
TF_ExplosiveAndFlammableProhibited
TF_KingpinToRearAxleLengthLimit_Meters
TF_SemiOrTractorWOneOrMoreTrailersProhibited

restricted turns feature class:

KingpinToRearAxleLengthLimit_Meters
SemiOrTractorWOneOrMoreTrailersProhibited

At 10.9.1 the network successfully published to ArcGIS Enterprise using the publish routing services utility tool. However at 11.0 this fails with the same network dataset due to the fieldname length. 

The fields are used in a descriptor called `Kingpin to Rear Axle Length Limit (meters)` and a restriction called `Semi or Tractor with One or More Trailers Prohibited`. The ExplosiveAndFlammableProhibited fields are not used by default. 

Another side effect with the tools I have noticed is that the field solvers are all created using VBScript which prevents them being included in a mobile map package. Is this tied to the lack of support for ArcGIS Pro at this time?

Should the tool automatically handle the source data from HERE having fieldnames that are too long?

**Comment by dbarretteuk** [comment]
@deelesh or @mmorang just follwoing up to see if anything has been considered for this issue? Is there a roadmap for migrating the HERE NAVSTREETS tools to ArcGIS Pro? 

Thanks,

Dave

**Comment by mmorang** [comment]
Just to add some further details based on your original question:
- The latest update to the Pro-based tools uses Python instead of VBScript for all field script evaluators, so you should be able to package the resulting network to a mobile map package.
- I don't _think_ there should be any problems publishing the resulting network to 11.x Server now, but please let us know if you're still having trouble.

I believe this issue has been resolved by the new ArcGIS Pro tool version, so I'm going to close it.  Please reopen if you're still having problems.
