### ISSUE TITLE
Tool keeps crashing (Process NAVSTREETS™ Street Data)

### ISSUE THREAD

**Issue by eslamgis90** [Esri/street-data-processing-tools#54]
I try using the tool "Process NAVSTREETS™ Street Data" for ArcGIS Desktop 10.8 or later. The tool keeps crashing.
Do you have any idea how to make it work?
I use ArcMap 10.8.2
![ToolError](https://github.com/Esri/street-data-processing-tools/assets/59332016/dd5076df-4eb6-45cd-9b37-da0e0011b93b)

**Comment by mmorang** [comment]
Do you have the 64-bit Background Geoprocessing extension?  The tool will not work with that extension, so you have to turn off background geoprocessing.  https://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/foreground-and-background-processing.htm

**Comment by mmorang** [comment]
Did you ever resolve this problem?  Crashes in ArcMap weren't unusual, since it was a 32-bit application that consequently had memory limitations.  Often running out of memory would lead to crashes.

A new version of the tool for processing HERE data is now available for ArcGIS Pro.  If you're still processing HERE data, please try this new tool version and let us know if you still experience hangs and crashes.  Because ArcGIS Pro is a 64-bit application and because the new tool was fully rewritten to be less resource intensive, we don't expect the same types of limitations that the old ArcMap version had.

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
